/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ifba.curso.view;

import com.ifba.curso.dao.CursoDao;
import com.ifba.curso.dao.CursoIDao;
import com.ifba.curso.entity.Curso;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author angra
 */
public class CursoListar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CursoListar.class.getName());

    /**
     * Creates new form CursoListar
     */
    public CursoListar() {
        initComponents();
        carregarCursos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaListarCurso = new javax.swing.JTable();
        btnExcluirCurso = new javax.swing.JButton();
        txtPesquisar = new java.awt.TextField();
        btnPesquisar = new javax.swing.JButton();
        btnAdicionarCurso = new javax.swing.JButton();
        btnEditarCurso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelaListarCurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Duração", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaListarCurso);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 62, -1, 369));

        btnExcluirCurso.setText("Excluir");
        btnExcluirCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirCursoActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluirCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, 28));

        txtPesquisar.setText("Pesquisar");
        getContentPane().add(txtPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 122, 28));

        btnPesquisar.setIcon(new javax.swing.ImageIcon("C:\\Users\\angra\\Documents\\NetBeansProjects\\prog03presistencia\\src\\main\\resources\\META-INF\\imagens\\lupa.png")); // NOI18N
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 22, -1, 28));

        btnAdicionarCurso.setText("Adicionar");
        btnAdicionarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarCursoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdicionarCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, 28));

        btnEditarCurso.setText("Editar");
        btnEditarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCursoActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditarCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, 28));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void carregarCursos() {
        DefaultTableModel tabela = (DefaultTableModel) tabelaListarCurso.getModel();
        tabela.setNumRows(0);

        CursoIDao cursoDao = new CursoDao();

        try {
            for(Curso curso : cursoDao.findAll()) {
                tabela.addRow(new Object[]{
                    curso.getId(),
                    curso.getNome(),
                    curso.getDuracao(),
                    curso.getDescricao()
                });
            } 
        } catch(Exception Erro) {
            JOptionPane.showMessageDialog(
                    null, 
                    "Erro ao carregar cursos\n" + Erro, 
                    "ERRO", 
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }
    
    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnExcluirCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirCursoActionPerformed
        // TODO add your handling code here:
      
        if(tabelaListarCurso.getSelectedRow() != -1) {
            int resposta = JOptionPane.showConfirmDialog(
                null, 
                "Excluir o curso selecionado?", 
                "Excluir curso",
                JOptionPane.YES_NO_OPTION
            );
        
            if(resposta == JOptionPane.YES_OPTION) {
                Long id = (Long) tabelaListarCurso.getValueAt(tabelaListarCurso.getSelectedRow(), 1);
            
                CursoIDao cursoDao = new CursoDao();
                cursoDao.delete(cursoDao.findById(id));
            
                carregarCursos();
            }
        } else {
            JOptionPane.showMessageDialog(
                    null, 
                    "Selecione um curso"
            );
        }
    }//GEN-LAST:event_btnExcluirCursoActionPerformed

    private void btnAdicionarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarCursoActionPerformed
        // TODO add your handling code here:
        AdicionarCurso adicionarCurso = new AdicionarCurso();
        adicionarCurso.setVisible(true);
    }//GEN-LAST:event_btnAdicionarCursoActionPerformed

    private void btnEditarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCursoActionPerformed
        if(tabelaListarCurso.getSelectedRow() != -1) {
            //Guarda o id do curso selecionado e envia para a tela cursoEditar
            Long id = (Long) tabelaListarCurso.getValueAt(tabelaListarCurso.getSelectedRow(), 1);
            EditarCurso editarCurso = new EditarCurso(this, id);
            editarCurso.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(
                    null, 
                    "Selecione um curso"
            );
        }
    }//GEN-LAST:event_btnEditarCursoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CursoListar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarCurso;
    private javax.swing.JButton btnEditarCurso;
    private javax.swing.JButton btnExcluirCurso;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaListarCurso;
    private java.awt.TextField txtPesquisar;
    // End of variables declaration//GEN-END:variables

   
}
